stages:
  - tests
  - angular_build
  - docker_build
  - pages
  - tag
  - deploy
  - release


tests:
  stage: tests
  tags: [node-14]
  only: [merge_requests]
  except: [pre-production, production]
  before_script:
  - apk add chromium
  - export CHROME_BIN=/usr/bin/chromium-browser
  script:
    - npm install
    - npm test

angular_build:
  stage: angular_build
  tags: [node-14]
  only: [master]
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

docker build image:
  stage: docker_build
  tags: [docker-dind]
  only: [master]
  script:
    - docker build -f environment/deploy_files/Dockerfile -t gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-dreg.nexxera.com
    - docker push gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master

docker tag to pre-production:
  stage: tag
  tags: [docker]
  only: [pre-production, /^hot-fix.*$/]
  script:
    - docker pull gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-dreg.nexxera.com
    - docker tag gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:master gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:pre-production
    - docker push gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:pre-production

deploy to dev:
  stage: deploy
  tags: [ansible-deploy]
  only: [master]
  environment:
    name: dev
    url: https://$CI_PROJECT_NAME-dev.cloudint.nexxera.com
  script:
    - ansible-playbook /ansible-deploy/site.yml -e deploy_vars=/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/environment/$CI_ENVIRONMENT_NAME.yml -e target=dev

deploy to tst:
  stage: deploy
  tags: [ansible-deploy]
  when: manual
  only: [master]
  environment:
    name: tst
    url: https://$CI_PROJECT_NAME-tst.cloudint.nexxera.com
  script:
    - ansible-playbook /ansible-deploy/site.yml -e deploy_vars=/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/environment/$CI_ENVIRONMENT_NAME.yml -e target=tst

deploy to qa:
  stage: deploy
  tags: [ansible-deploy]
  only: [pre-production]
  environment:
    name: qa
    url: https://$CI_PROJECT_NAME-qa.cloudint.nexxera.com
  script:
    - ansible-playbook /ansible-deploy/site.yml -e deploy_vars=/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/environment/$CI_ENVIRONMENT_NAME.yml -e target=qa

release to production:
  stage: release
  tags: [docker]
  only: [production]
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-dreg.nexxera.com
    - docker pull gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:pre-production
    - docker tag gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:pre-production gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:production
    - docker push gitlab-dreg.nexxera.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:production
