// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
export const environment = {
  production: true,
  APIs: {
    GATEWAY: 'ENV_API_GATEWAY',
    NIXFEEQA: 'ENV_NIXFEEQA',
    BRASILAPI: 'ENV_BRASIL_API',
    VIRTUAL_ACCOUNT_CARD: 'ENV_VIRTUAL_ACCOUNT_CARD_API',
  },
  SUPPORT_EMAIL: 'ENV_SUPPORT_EMAIL',
  NO_REPLY_EMAIL: 'ENV_NO_REPLY_EMAIL',
  KEYS: {
    APP_NAME: 'KEY_APP_NAME',
    GROUP_ID: 'KEY_GROUP_ID',
    SELF_HIRING_CODE: 'KEY_SELF_HIRING_CODE',
    SESSION_TIMEOUT: 'KEY_SESSION_TIMEOUT',
  },
};
