// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: false,
  APIs: {
    GATEWAY: 'https://apigateway-qa.nexxera.com',
    NIXFEEQA: 'https://apigateway-qa.nexxera.com',
    BRASILAPI: 'https://brasilapi.com.br/api/cep/v1',
    VIRTUAL_ACCOUNT_CARD:
      'https://virtual-account-card-web-qa.cloudint.nexxera.com/#/card/',
  },
  SUPPORT_EMAIL: 'andrey.morais@nexxera.com',
  NO_REPLY_EMAIL: 'no-reply@nexxera.com',
  KEYS: {
    APP_NAME: 'NIX_EMPRESAS',
    GROUP_ID: 'f5ab6473-457c-4864-a8b5-e04c4263ef8e',
    SELF_HIRING_CODE: 'nexxera',
    SESSION_TIMEOUT: '9000',
  },
};
