apps:
  - name: "nix-empresas-web"
    deploy_name: "nix-empresas-web"
    group: "nix-dev"
    image: "gitlab-dreg.nexxera.com/nix/nix-empresas-web:master"
    routes:
      - name: "nix-empresas-web-dev"
        hostname: "nix-empresas-web-dev"
        port: "8080"
        path: ""
        certificate: ""
    env_vars:
      - API_GATEWAY='https://apigateway-tst.nexxera.com'
      - NIXFEEQA='https://apigateway-qa.nexxera.com'
      - BRASILAPI='https://brasilapi.com.br/api/cep/v1'
      - VIRTUAL_ACCOUNT_CARD='https://virtual-account-card-web-tst.cloudint.nexxera.com/#/card/'
      - SUPPORT_EMAIL='andrey.morais@nexxera.com'
      - NO_REPLY_EMAIL='no-reply@nexxera.com'
      - KEY_APP_NAME='NIX_EMPRESAS'
      - KEY_GROUP_ID='f5ab6473-457c-4864-a8b5-e04c4263ef8e'
      - KEY_SELF_HIRING_CODE='nexxera'
      - KEY_SESSION_TIMEOUT='420'
