import { IAccountType, IBank } from './bank.model';

export const ACCOUNTTYPES: IAccountType[] = [
  { label: 'Corrente', value: '0' },
  { label: 'Poupança', value: '1' },
];

export const BANKLIST: IBank[] = [
  {
    ispb: '13140088',
    short_name: 'ACESSO SOLUCOES PAGAMENTO SA',
    long_name: 'Acesso Soluções de Pagamento S.A.',
    compe_code: '332',
  },
  {
    ispb: '02318507',
    short_name: 'BCO KEB HANA DO BRASIL S.A.',
    long_name: 'BANCO KEB HANA DO BRASIL S.A.',
    compe_code: '757',
  },
  {
    ispb: '02038232',
    short_name: 'BANCOOB',
    long_name: 'BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB',
    compe_code: '756',
  },
  {
    ispb: '62073200',
    short_name: 'BOFA MERRILL LYNCH BM S.A.',
    long_name: 'Bank of America Merrill Lynch Banco Múltiplo S.A.',
    compe_code: '755',
  },
  {
    ispb: '76543115',
    short_name: 'BANCO SISTEMA',
    long_name: 'Banco Sistema S.A.',
    compe_code: '754',
  },
  {
    ispb: '74828799',
    short_name: 'NOVO BCO CONTINENTAL S.A. - BM',
    long_name: 'Novo Banco Continental S.A. - Banco Múltiplo',
    compe_code: '753',
  },
  {
    ispb: '01522368',
    short_name: 'BCO BNP PARIBAS BRASIL S A',
    long_name: 'Banco BNP Paribas Brasil S.A.',
    compe_code: '752',
  },
  {
    ispb: '29030467',
    short_name: 'SCOTIABANK BRASIL',
    long_name: 'Scotiabank Brasil S.A. Banco Múltiplo',
    compe_code: '751',
  },
  {
    ispb: '01181521',
    short_name: 'BCO COOPERATIVO SICREDI S.A.',
    long_name: 'BANCO COOPERATIVO SICREDI S.A.',
    compe_code: '748',
  },
  {
    ispb: '01023570',
    short_name: 'BCO RABOBANK INTL BRASIL S.A.',
    long_name: 'Banco Rabobank International Brasil S.A.',
    compe_code: '747',
  },
  {
    ispb: '30723886',
    short_name: 'BCO MODAL S.A.',
    long_name: 'Banco Modal S.A.',
    compe_code: '746',
  },
  {
    ispb: '33479023',
    short_name: 'BCO CITIBANK S.A.',
    long_name: 'Banco Citibank S.A.',
    compe_code: '745',
  },
  {
    ispb: '00795423',
    short_name: 'BANCO SEMEAR',
    long_name: 'Banco Semear S.A.',
    compe_code: '743',
  },
  {
    ispb: '00517645',
    short_name: 'BCO RIBEIRAO PRETO S.A.',
    long_name: 'BANCO RIBEIRAO PRETO S.A.',
    compe_code: '741',
  },
  {
    ispb: '00558456',
    short_name: 'BCO CETELEM S.A.',
    long_name: 'Banco Cetelem S.A.',
    compe_code: '739',
  },
  {
    ispb: '78632767',
    short_name: 'BCO OURINVEST S.A.',
    long_name: 'Banco Ourinvest S.A.',
    compe_code: '712',
  },
  {
    ispb: '62232889',
    short_name: 'BCO DAYCOVAL S.A',
    long_name: 'Banco Daycoval S.A.',
    compe_code: '707',
  },
  {
    ispb: '59588111',
    short_name: 'BCO VOTORANTIM S.A.',
    long_name: 'Banco Votorantim S.A.',
    compe_code: '655',
  },
  {
    ispb: '92874270',
    short_name: 'BCO DIGIMAIS S.A.',
    long_name: 'BANCO DIGIMAIS S.A.',
    compe_code: '654',
  },
  {
    ispb: '61024352',
    short_name: 'BCO INDUSVAL S.A.',
    long_name: 'BANCO INDUSVAL S.A.',
    compe_code: '653',
  },
  {
    ispb: '60872504',
    short_name: 'ITAÚ UNIBANCO HOLDING S.A.',
    long_name: 'Itaú Unibanco Holding S.A.',
    compe_code: '652',
  },
  {
    ispb: '62144175',
    short_name: 'BCO PINE S.A.',
    long_name: 'Banco Pine S.A.',
    compe_code: '643',
  },
  {
    ispb: '60889128',
    short_name: 'BCO SOFISA S.A.',
    long_name: 'BANCO SOFISA S.A.',
    compe_code: '637',
  },
  {
    ispb: '17351180',
    short_name: 'BCO TRIANGULO S.A.',
    long_name: 'BANCO TRIANGULO S.A.',
    compe_code: '634',
  },
  {
    ispb: '68900810',
    short_name: 'BCO RENDIMENTO S.A.',
    long_name: 'Banco Rendimento S.A.',
    compe_code: '633',
  },
  {
    ispb: '58497702',
    short_name: 'SMARTBANK',
    long_name: 'Banco Smartbank S.A.',
    compe_code: '630',
  },
  {
    ispb: '61348538',
    short_name: 'BCO C6 CONSIG',
    long_name: 'BANCO C6 CONSIGNADO S.A.',
    compe_code: '626',
  },
  {
    ispb: '59285411',
    short_name: 'BANCO PAN',
    long_name: 'Banco Pan S.A.',
    compe_code: '623',
  },
  {
    ispb: '60850229',
    short_name: 'OMNI BANCO S.A.',
    long_name: 'Omni Banco S.A.',
    compe_code: '613',
  },
  {
    ispb: '31880826',
    short_name: 'BCO GUANABARA S.A.',
    long_name: 'Banco Guanabara S.A.',
    compe_code: '612',
  },
  {
    ispb: '61820817',
    short_name: 'BCO PAULISTA S.A.',
    long_name: 'Banco Paulista S.A.',
    compe_code: '611',
  },
  {
    ispb: '78626983',
    short_name: 'BCO VR S.A.',
    long_name: 'Banco VR S.A.',
    compe_code: '610',
  },
  {
    ispb: '31895683',
    short_name: 'BCO INDUSTRIAL DO BRASIL S.A.',
    long_name: 'Banco Industrial do Brasil S.A.',
    compe_code: '604',
  },
  {
    ispb: '59118133',
    short_name: 'BCO LUSO BRASILEIRO S.A.',
    long_name: 'Banco Luso Brasileiro S.A.',
    compe_code: '600',
  },
  {
    ispb: '17352220',
    short_name: 'SENSO CCVM S.A.',
    long_name: 'SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A',
    compe_code: '545',
  },
  {
    ispb: '32062580',
    short_name: 'BCO CREDIT SUISSE S.A.',
    long_name: 'Banco Credit Suisse (Brasil) S.A.',
    compe_code: '505',
  },
  {
    ispb: '44189447',
    short_name: 'BCO LA PROVINCIA B AIRES BCE',
    long_name: 'Banco de La Provincia de Buenos Aires',
    compe_code: '495',
  },
  {
    ispb: '49336860',
    short_name: 'ING BANK N.V.',
    long_name: 'ING Bank N.V.',
    compe_code: '492',
  },
  {
    ispb: '46518205',
    short_name: 'JPMORGAN CHASE BANK',
    long_name: 'JPMorgan Chase Bank, National Association',
    compe_code: '488',
  },
  {
    ispb: '62331228',
    short_name: 'DEUTSCHE BANK S.A.BCO ALEMAO',
    long_name: 'DEUTSCHE BANK S.A. - BANCO ALEMAO',
    compe_code: '487',
  },
  {
    ispb: '60394079',
    short_name: 'BCO ITAUBANK S.A.',
    long_name: 'Banco ItauBank S.A.',
    compe_code: '479',
  },
  {
    ispb: '33042953',
    short_name: 'CITIBANK N.A.',
    long_name: 'Citibank N.A.',
    compe_code: '477',
  },
  {
    ispb: '33466988',
    short_name: 'BCO CAIXA GERAL BRASIL S.A.',
    long_name: 'Banco Caixa Geral - Brasil S.A.',
    compe_code: '473',
  },
  {
    ispb: '60518222',
    short_name: 'BCO SUMITOMO MITSUI BRASIL S.A.',
    long_name: 'Banco Sumitomo Mitsui Brasileiro S.A.',
    compe_code: '464',
  },
  {
    ispb: '60498557',
    short_name: 'BCO MUFG BRASIL S.A.',
    long_name: 'Banco MUFG Brasil S.A.',
    compe_code: '456',
  },
  {
    ispb: '58160789',
    short_name: 'BCO SAFRA S.A.',
    long_name: 'Banco Safra S.A.',
    compe_code: '422',
  },
  {
    ispb: '15173776',
    short_name: 'BCO CAPITAL S.A.',
    long_name: 'BANCO CAPITAL S.A.',
    compe_code: '412',
  },
  {
    ispb: '37880206',
    short_name: 'CORA SCD S.A.',
    long_name: 'CORA SOCIEDADE DE CRÉDITO DIRETO S.A.',
    compe_code: '403',
  },
  {
    ispb: '01701201',
    short_name: 'KIRTON BANK',
    long_name: 'Kirton Bank S.A. - Banco Múltiplo',
    compe_code: '399',
  },
  {
    ispb: '13884775',
    short_name: 'HUB PAGAMENTOS',
    long_name: 'HUB PAGAMENTOS S.A',
    compe_code: '396',
  },
  {
    ispb: '07207996',
    short_name: 'BCO BRADESCO FINANC. S.A.',
    long_name: 'Banco Bradesco Financiamentos S.A.',
    compe_code: '394',
  },
  {
    ispb: '59109165',
    short_name: 'BCO VOLKSWAGEN S.A',
    long_name: 'Banco Volkswagen S.A.',
    compe_code: '393',
  },
  {
    ispb: '08240446',
    short_name: 'CCR DE IBIAM',
    long_name: 'COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM',
    compe_code: '391',
  },
  {
    ispb: '59274605',
    short_name: 'BCO GM S.A.',
    long_name: 'BANCO GM S.A.',
    compe_code: '390',
  },
  {
    ispb: '17184037',
    short_name: 'BCO MERCANTIL DO BRASIL S.A.',
    long_name: 'Banco Mercantil do Brasil S.A.',
    compe_code: '389',
  },
  {
    ispb: '03215790',
    short_name: 'BCO TOYOTA DO BRASIL S.A.',
    long_name: 'Banco Toyota do Brasil S.A.',
    compe_code: '387',
  },
  {
    ispb: '21018182',
    short_name: 'JUNO',
    long_name: 'BOLETOBANCÁRIO.COM TECNOLOGIA DE PAGAMENTOS LTDA.',
    compe_code: '383',
  },
  {
    ispb: '04307598',
    short_name: 'FIDUCIA SCMEPP LTDA',
    long_name:
      'FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L',
    compe_code: '382',
  },
  {
    ispb: '60814191',
    short_name: 'BCO MERCEDES-BENZ S.A.',
    long_name: 'BANCO MERCEDES-BENZ DO BRASIL S.A.',
    compe_code: '381',
  },
  {
    ispb: '01658426',
    short_name: 'CECM COOPERFORTE',
    long_name:
      'COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FUNCIONÁRIOS DE INSTIT',
    compe_code: '379',
  },
  {
    ispb: '01852137',
    short_name: 'BBC LEASING',
    long_name: 'BBC LEASING S.A. - ARRENDAMENTO MERCANTIL',
    compe_code: '378',
  },
  {
    ispb: '17826860',
    short_name: 'MS SCMEPP LTDA',
    long_name:
      'MS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA',
    compe_code: '377',
  },
  {
    ispb: '33172537',
    short_name: 'BCO J.P. MORGAN S.A.',
    long_name: 'BANCO J.P. MORGAN S.A.',
    compe_code: '376',
  },
  {
    ispb: '27351731',
    short_name: 'REALIZE CFI S.A.',
    long_name: 'REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
    compe_code: '374',
  },
  {
    ispb: '35977097',
    short_name: 'UP.P SEP S.A.',
    long_name: 'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.',
    compe_code: '373',
  },
  {
    ispb: '92875780',
    short_name: 'WARREN CVMC LTDA',
    long_name: 'WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.',
    compe_code: '371',
  },
  {
    ispb: '61088183',
    short_name: 'BCO MIZUHO S.A.',
    long_name: 'Banco Mizuho do Brasil S.A.',
    compe_code: '370',
  },
  {
    ispb: '08357240',
    short_name: 'BCO CSF S.A.',
    long_name: 'Banco CSF S.A.',
    compe_code: '368',
  },
  {
    ispb: '34711571',
    short_name: 'VITREO DTVM S.A.',
    long_name: 'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
    compe_code: '367',
  },
  {
    ispb: '61533584',
    short_name: 'BCO SOCIETE GENERALE BRASIL',
    long_name: 'BANCO SOCIETE GENERALE BRASIL S.A.',
    compe_code: '366',
  },
  {
    ispb: '68757681',
    short_name: 'SOLIDUS S.A. CCVM',
    long_name: 'SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS',
    compe_code: '365',
  },
  {
    ispb: '09089356',
    short_name: 'GERENCIANET PAGTOS BRASIL LTDA',
    long_name: 'GERENCIANET PAGAMENTOS DO BRASIL LTDA',
    compe_code: '364',
  },
  {
    ispb: '62285390',
    short_name: 'SOCOPA SC PAULISTA S.A.',
    long_name: 'SOCOPA SOCIEDADE CORRETORA PAULISTA S.A.',
    compe_code: '363',
  },
  {
    ispb: '01027058',
    short_name: 'CIELO S.A.',
    long_name: 'CIELO S.A.',
    compe_code: '362',
  },
  {
    ispb: '02276653',
    short_name: 'TRINUS CAPITAL DTVM',
    long_name:
      'TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
    compe_code: '360',
  },
  {
    ispb: '05351887',
    short_name: 'ZEMA CFI S/A',
    long_name: 'ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A',
    compe_code: '359',
  },
  {
    ispb: '34335592',
    short_name: 'ÓTIMO SCD S.A.',
    long_name: 'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.',
    compe_code: '355',
  },
  {
    ispb: '52904364',
    short_name: 'NECTON INVESTIMENTOS S.A CVM',
    long_name:
      'NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES',
    compe_code: '354',
  },
  {
    ispb: '29162769',
    short_name: 'TORO CTVM LTDA',
    long_name: 'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    compe_code: '352',
  },
  {
    ispb: '01330387',
    short_name: 'CREHNOR LARANJEIRAS',
    long_name:
      'COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA DO CE',
    compe_code: '350',
  },
  {
    ispb: '27214112',
    short_name: 'AL5 S.A. CFI',
    long_name: 'AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
    compe_code: '349',
  },
  {
    ispb: '33264668',
    short_name: 'BCO XP S.A.',
    long_name: 'Banco XP S.A.',
    compe_code: '348',
  },
  {
    ispb: '24537861',
    short_name: 'FFA SCMEPP LTDA.',
    long_name:
      'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.',
    compe_code: '343',
  },
  {
    ispb: '32997490',
    short_name: 'CREDITAS SCD',
    long_name: 'Creditas Sociedade de Crédito Direto S.A.',
    compe_code: '342',
  },
  {
    ispb: '60701190',
    short_name: 'ITAÚ UNIBANCO S.A.',
    long_name: 'ITAÚ UNIBANCO S.A.',
    compe_code: '341',
  },
  {
    ispb: '09554480',
    short_name: 'SUPER PAGAMENTOS E ADMINISTRACAO DE MEIOS ELETRONICOS S.A.',
    long_name: 'Super Pagamentos e Administração de Meios Eletrônicos S.A.',
    compe_code: '340',
  },
  {
    ispb: '31872495',
    short_name: 'BCO C6 S.A.',
    long_name: 'Banco C6 S.A.',
    compe_code: '336',
  },
  {
    ispb: '27098060',
    short_name: 'BANCO DIGIO',
    long_name: 'Banco Digio S.A.',
    compe_code: '335',
  },
  {
    ispb: '13673855',
    short_name: 'FRAM CAPITAL DTVM S.A.',
    long_name:
      'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.',
    compe_code: '331',
  },
  {
    ispb: '00556603',
    short_name: 'BANCO BARI S.A.',
    long_name: 'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.',
    compe_code: '330',
  },
  {
    ispb: '32402502',
    short_name: 'QI SCD S.A.',
    long_name: 'QI Sociedade de Crédito Direto S.A.',
    compe_code: '329',
  },
  {
    ispb: '03311443',
    short_name: 'PARATI - CFI S.A.',
    long_name: 'PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
    compe_code: '326',
  },
  {
    ispb: '13293225',
    short_name: 'ÓRAMA DTVM S.A.',
    long_name: 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.',
    compe_code: '325',
  },
  {
    ispb: '21332862',
    short_name: 'CARTOS SCD S.A.',
    long_name: 'CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.',
    compe_code: '324',
  },
  {
    ispb: '10573521',
    short_name: 'MERCADO PAGO',
    long_name: 'MERCADOPAGO.COM REPRESENTACOES LTDA.',
    compe_code: '323',
  },
  {
    ispb: '01073966',
    short_name: 'CCR DE ABELARDO LUZ',
    long_name:
      'Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz',
    compe_code: '322',
  },
  {
    ispb: '18188384',
    short_name: 'CREFAZ SCMEPP LTDA',
    long_name:
      'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT',
    compe_code: '321',
  },
  {
    ispb: '07450604',
    short_name: 'BCO CCB BRASIL S.A.',
    long_name: 'China Construction Bank (Brasil) Banco Múltiplo S/A',
    compe_code: '320',
  },
  {
    ispb: '11495073',
    short_name: 'OM DTVM LTDA',
    long_name: 'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    compe_code: '319',
  },
  {
    ispb: '61186680',
    short_name: 'BCO BMG S.A.',
    long_name: 'Banco BMG S.A.',
    compe_code: '318',
  },
  {
    ispb: '03502968',
    short_name: 'PI DTVM S.A.',
    long_name: 'PI Distribuidora de Títulos e Valores Mobiliários S.A.',
    compe_code: '315',
  },
  {
    ispb: '16927221',
    short_name: 'AMAZÔNIA CC LTDA.',
    long_name: 'AMAZÔNIA CORRETORA DE CÂMBIO LTDA.',
    compe_code: '313',
  },
  {
    ispb: '22610500',
    short_name: 'VORTX DTVM LTDA.',
    long_name: 'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
    compe_code: '310',
  },
  {
    ispb: '14190547',
    short_name: 'CAMBIONET CC LTDA',
    long_name: 'CAMBIONET CORRETORA DE CÂMBIO LTDA.',
    compe_code: '309',
  },
  {
    ispb: '03751794',
    short_name: 'TERRA INVESTIMENTOS DTVM',
    long_name:
      'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.',
    compe_code: '307',
  },
  {
    ispb: '40303299',
    short_name: 'PORTOPAR DTVM LTDA',
    long_name: 'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
    compe_code: '306',
  },
  {
    ispb: '13370835',
    short_name: 'BPP IP S.A.',
    long_name: 'BPP Instituição de Pagamento S.A.',
    compe_code: '301',
  },
  {
    ispb: '33042151',
    short_name: 'BCO LA NACION ARGENTINA',
    long_name: 'Banco de la Nacion Argentina',
    compe_code: '300',
  },
  {
    ispb: '04814563',
    short_name: 'SOROCRED CFI S.A.',
    long_name: 'SOROCRED CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
    compe_code: '299',
  },
  {
    ispb: '17772370',
    short_name: 'VIPS CC LTDA.',
    long_name: 'Vips Corretora de Câmbio Ltda.',
    compe_code: '298',
  },
  {
    ispb: '04062902',
    short_name: 'VISION S.A. CC',
    long_name: 'VISION S.A. CORRETORA DE CAMBIO',
    compe_code: '296',
  },
  {
    ispb: '71590442',
    short_name: 'LASTRO RDV DTVM LTDA',
    long_name:
      'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.',
    compe_code: '293',
  },
  {
    ispb: '28650236',
    short_name: 'BS2 DTVM S.A.',
    long_name: 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.',
    compe_code: '292',
  },
  {
    ispb: '08561701',
    short_name: 'PAGSEGURO',
    long_name: 'Pagseguro Internet S.A.',
    compe_code: '290',
  },
  {
    ispb: '94968518',
    short_name: 'DECYSEO CC LTDA.',
    long_name: 'DECYSEO CORRETORA DE CAMBIO LTDA.',
    compe_code: '289',
  },
  {
    ispb: '62237649',
    short_name: 'CAROL DTVM LTDA.',
    long_name: 'CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
    compe_code: '288',
  },
  {
    ispb: '07853842',
    short_name: 'CCR DE OURO',
    long_name: 'COOPERATIVA DE CRÉDITO RURAL DE OURO SULCREDI/OURO',
    compe_code: '286',
  },
  {
    ispb: '71677850',
    short_name: 'FRENTE CC LTDA.',
    long_name: 'Frente Corretora de Câmbio Ltda.',
    compe_code: '285',
  },
  {
    ispb: '89960090',
    short_name: 'RB CAPITAL INVESTIMENTOS DTVM LTDA.',
    long_name:
      'RB CAPITAL INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LIMITADA',
    compe_code: '283',
  },
  {
    ispb: '76461557',
    short_name: 'CCR COOPAVEL',
    long_name: 'Cooperativa de Crédito Rural Coopavel',
    compe_code: '281',
  },
  {
    ispb: '23862762',
    short_name: 'AVISTA S.A. CFI',
    long_name: 'Avista S.A. Crédito, Financiamento e Investimento',
    compe_code: '280',
  },
  {
    ispb: '26563270',
    short_name: 'CCR DE PRIMAVERA DO LESTE',
    long_name: 'COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE',
    compe_code: '279',
  },
  {
    ispb: '27652684',
    short_name: 'GENIAL INVESTIMENTOS CVM S.A.',
    long_name: 'Genial Investimentos Corretora de Valores Mobiliários S.A.',
    compe_code: '278',
  },
  {
    ispb: '11970623',
    short_name: 'SENFF S.A. - CFI',
    long_name: 'Senff S.A. - Crédito, Financiamento e Investimento',
    compe_code: '276',
  },
  {
    ispb: '11581339',
    short_name: 'MONEY PLUS SCMEPP LTDA',
    long_name:
      'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT',
    compe_code: '274',
  },
  {
    ispb: '08253539',
    short_name: 'CCR DE SÃO MIGUEL DO OESTE',
    long_name:
      'Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel',
    compe_code: '273',
  },
  {
    ispb: '00250699',
    short_name: 'AGK CC S.A.',
    long_name: 'AGK CORRETORA DE CAMBIO S.A.',
    compe_code: '272',
  },
  {
    ispb: '27842177',
    short_name: 'IB CCTVM S.A.',
    long_name: 'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
    compe_code: '271',
  },
  {
    ispb: '61444949',
    short_name: 'SAGITUR CC LTDA',
    long_name: 'Sagitur Corretora de Câmbio Ltda.',
    compe_code: '270',
  },
  {
    ispb: '53518684',
    short_name: 'BCO HSBC S.A.',
    long_name: 'BANCO HSBC S.A.',
    compe_code: '269',
  },
  {
    ispb: '14511781',
    short_name: 'BARI CIA HIPOTECÁRIA',
    long_name: 'BARI COMPANHIA HIPOTECÁRIA',
    compe_code: '268',
  },
  {
    ispb: '33132044',
    short_name: 'BCO CEDULA S.A.',
    long_name: 'BANCO CEDULA S.A.',
    compe_code: '266',
  },
  {
    ispb: '33644196',
    short_name: 'BCO FATOR S.A.',
    long_name: 'Banco Fator S.A.',
    compe_code: '265',
  },
  {
    ispb: '18236120',
    short_name: 'NU PAGAMENTOS S.A.',
    long_name: 'Nu Pagamentos S.A.',
    compe_code: '260',
  },
  {
    ispb: '08609934',
    short_name: 'MONEYCORP BCO DE CÂMBIO S.A.',
    long_name: 'MONEYCORP BANCO DE CÂMBIO S.A.',
    compe_code: '259',
  },
  {
    ispb: '14388334',
    short_name: 'PARANA BCO S.A.',
    long_name: 'PARANÁ BANCO S.A.',
    compe_code: '254',
  },
  {
    ispb: '52937216',
    short_name: 'BEXS CC S.A.',
    long_name: 'Bexs Corretora de Câmbio S/A',
    compe_code: '253',
  },
  {
    ispb: '50585090',
    short_name: 'BCV',
    long_name: 'BCV - BANCO DE CRÉDITO E VAREJO S.A.',
    compe_code: '250',
  },
  {
    ispb: '61182408',
    short_name: 'BANCO INVESTCRED UNIBANCO S.A.',
    long_name: 'Banco Investcred Unibanco S.A.',
    compe_code: '249',
  },
  {
    ispb: '28195667',
    short_name: 'BCO ABC BRASIL S.A.',
    long_name: 'Banco ABC Brasil S.A.',
    compe_code: '246',
  },
  {
    ispb: '33923798',
    short_name: 'BCO MÁXIMA S.A.',
    long_name: 'Banco Máxima S.A.',
    compe_code: '243',
  },
  {
    ispb: '31597552',
    short_name: 'BCO CLASSICO S.A.',
    long_name: 'BANCO CLASSICO S.A.',
    compe_code: '241',
  },
  {
    ispb: '60746948',
    short_name: 'BCO BRADESCO S.A.',
    long_name: 'Banco Bradesco S.A.',
    compe_code: '237',
  },
  {
    ispb: '62421979',
    short_name: 'BANCO CIFRA',
    long_name: 'Banco Cifra S.A.',
    compe_code: '233',
  },
  {
    ispb: '58616418',
    short_name: 'BCO FIBRA S.A.',
    long_name: 'Banco Fibra S.A.',
    compe_code: '224',
  },
  {
    ispb: '75647891',
    short_name: 'BCO CRÉDIT AGRICOLE BR S.A.',
    long_name: 'BANCO CRÉDIT AGRICOLE BRASIL S.A.',
    compe_code: '222',
  },
  {
    ispb: '71027866',
    short_name: 'BCO BS2 S.A.',
    long_name: 'Banco BS2 S.A.',
    compe_code: '218',
  },
  {
    ispb: '91884981',
    short_name: 'BANCO JOHN DEERE S.A.',
    long_name: 'Banco John Deere S.A.',
    compe_code: '217',
  },
  {
    ispb: '54403563',
    short_name: 'BCO ARBI S.A.',
    long_name: 'Banco Arbi S.A.',
    compe_code: '213',
  },
  {
    ispb: '92894922',
    short_name: 'BANCO ORIGINAL',
    long_name: 'Banco Original S.A.',
    compe_code: '212',
  },
  {
    ispb: '30306294',
    short_name: 'BANCO BTG PACTUAL S.A.',
    long_name: 'Banco BTG Pactual S.A.',
    compe_code: '208',
  },
  {
    ispb: '16501555',
    short_name: 'STONE PAGAMENTOS S.A.',
    long_name: 'Stone Pagamentos S.A.',
    compe_code: '197',
  },
  {
    ispb: '32648370',
    short_name: 'FAIR CC S.A.',
    long_name: 'FAIR CORRETORA DE CAMBIO S.A.',
    compe_code: '196',
  },
  {
    ispb: '20155248',
    short_name: 'PARMETAL DTVM LTDA',
    long_name: 'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    compe_code: '194',
  },
  {
    ispb: '04257795',
    short_name: 'NOVA FUTURA CTVM LTDA.',
    long_name: 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.',
    compe_code: '191',
  },
  {
    ispb: '03973814',
    short_name: 'SERVICOOP',
    long_name:
      'SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN',
    compe_code: '190',
  },
  {
    ispb: '07512441',
    short_name: 'HS FINANCEIRA',
    long_name: 'HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS',
    compe_code: '189',
  },
  {
    ispb: '33775974',
    short_name: 'ATIVA S.A. INVESTIMENTOS CCTVM',
    long_name:
      'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES',
    compe_code: '188',
  },
  {
    ispb: '17298092',
    short_name: 'BCO ITAÚ BBA S.A.',
    long_name: 'Banco Itaú BBA S.A.',
    compe_code: '184',
  },
  {
    ispb: '09210106',
    short_name: 'SOCRED SA - SCMEPP',
    long_name:
      'SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P',
    compe_code: '183',
  },
  {
    ispb: '02685483',
    short_name: 'CM CAPITAL MARKETS CCTVM LTDA',
    long_name:
      'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    compe_code: '180',
  },
  {
    ispb: '65913436',
    short_name: 'GUIDE',
    long_name: 'Guide Investimentos S.A. Corretora de Valores',
    compe_code: '177',
  },
  {
    ispb: '43180355',
    short_name: 'PEFISA S.A. - CFI',
    long_name: 'PEFISA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
    compe_code: '174',
  },
  {
    ispb: '13486793',
    short_name: 'BRL TRUST DTVM SA',
    long_name: 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.',
    compe_code: '173',
  },
  {
    ispb: '71371686',
    short_name: 'BCO OLÉ CONSIGNADO S.A.',
    long_name: 'BANCO OLÉ CONSIGNADO S.A.',
    compe_code: '169',
  },
  {
    ispb: '23522214',
    short_name: 'COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO',
    long_name: 'Commerzbank Brasil S.A. - Banco Múltiplo',
    compe_code: '163',
  },
  {
    ispb: '05442029',
    short_name: 'CASA CREDITO S.A. SCM',
    long_name: 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor',
    compe_code: '159',
  },
  {
    ispb: '09105360',
    short_name: 'ICAP DO BRASIL CTVM LTDA.',
    long_name:
      'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.',
    compe_code: '157',
  },
  {
    ispb: '15581638',
    short_name: 'FACTA S.A. CFI',
    long_name: 'Facta Financeira S.A. - Crédito Financiamento e Investimento',
    compe_code: '149',
  },
  {
    ispb: '24074692',
    short_name: 'GUITTA CC LTDA',
    long_name: 'GUITTA CORRETORA DE CAMBIO LTDA.',
    compe_code: '146',
  },
  {
    ispb: '50579044',
    short_name: 'LEVYCAM CCV LTDA',
    long_name: 'LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.',
    compe_code: '145',
  },
  {
    ispb: '13059145',
    short_name: 'BEXS BCO DE CAMBIO S.A.',
    long_name: 'BEXS BANCO DE CÂMBIO S/A',
    compe_code: '144',
  },
  {
    ispb: '02992317',
    short_name: 'TREVISO CC S.A.',
    long_name: 'Treviso Corretora de Câmbio S.A.',
    compe_code: '143',
  },
  {
    ispb: '16944141',
    short_name: 'BROKER BRASIL CC LTDA.',
    long_name: 'Broker Brasil Corretora de Câmbio Ltda.',
    compe_code: '142',
  },
  {
    ispb: '62169875',
    short_name: 'EASYNVEST - TÍTULO CV SA',
    long_name: 'Easynvest - Título Corretora de Valores SA',
    compe_code: '140',
  },
  {
    ispb: '55230916',
    short_name: 'INTESA SANPAOLO BRASIL S.A. BM',
    long_name: 'Intesa Sanpaolo Brasil S.A. - Banco Múltiplo',
    compe_code: '139',
  },
  {
    ispb: '10853017',
    short_name: 'GET MONEY CC LTDA',
    long_name: 'Get Money Corretora de Câmbio S.A.',
    compe_code: '138',
  },
  {
    ispb: '00315557',
    short_name: 'CONF NAC COOP CENTRAIS UNICRED',
    long_name:
      'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASI',
    compe_code: '136',
  },
  {
    ispb: '33862244',
    short_name: 'BGC LIQUIDEZ DTVM LTDA',
    long_name:
      'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    compe_code: '134',
  },
  {
    ispb: '10398952',
    short_name: 'CRESOL CONFEDERAÇÃO',
    long_name:
      'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E',
    compe_code: '133',
  },
  {
    ispb: '17453575',
    short_name: 'ICBC DO BRASIL BM S.A.',
    long_name: 'ICBC do Brasil Banco Múltiplo S.A.',
    compe_code: '132',
  },
  {
    ispb: '61747085',
    short_name: 'TULLETT PREBON BRASIL CVC LTDA',
    long_name: 'TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA',
    compe_code: '131',
  },
  {
    ispb: '09313766',
    short_name: 'CARUANA SCFI',
    long_name:
      'CARUANA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
    compe_code: '130',
  },
  {
    ispb: '18520834',
    short_name: 'UBS BRASIL BI S.A.',
    long_name: 'UBS Brasil Banco de Investimento S.A.',
    compe_code: '129',
  },
  {
    ispb: '19307785',
    short_name: 'MS BANK S.A. BCO DE CÂMBIO',
    long_name: 'MS Bank S.A. Banco de Câmbio',
    compe_code: '128',
  },
  {
    ispb: '09512542',
    short_name: 'CODEPE CVC S.A.',
    long_name: 'Codepe Corretora de Valores e Câmbio S.A.',
    compe_code: '127',
  },
  {
    ispb: '13220493',
    short_name: 'BR PARTNERS BI',
    long_name: 'BR Partners Banco de Investimento S.A.',
    compe_code: '126',
  },
  {
    ispb: '45246410',
    short_name: 'PLURAL BCO BM',
    long_name: 'Plural S.A. Banco Múltiplo',
    compe_code: '125',
  },
  {
    ispb: '15357060',
    short_name: 'BCO WOORI BANK DO BRASIL S.A.',
    long_name: 'Banco Woori Bank do Brasil S.A.',
    compe_code: '124',
  },
  {
    ispb: '33147315',
    short_name: 'BCO BRADESCO BERJ S.A.',
    long_name: 'Banco Bradesco BERJ S.A.',
    compe_code: '122',
  },
  {
    ispb: '10664513',
    short_name: 'BCO AGIBANK S.A.',
    long_name: 'Banco Agibank S.A.',
    compe_code: '121',
  },
  {
    ispb: '33603457',
    short_name: 'BCO RODOBENS S.A.',
    long_name: 'BANCO RODOBENS S.A.',
    compe_code: '120',
  },
  {
    ispb: '13720915',
    short_name: 'BCO WESTERN UNION',
    long_name: 'Banco Western Union do Brasil S.A.',
    compe_code: '119',
  },
  {
    ispb: '92856905',
    short_name: 'ADVANCED CC LTDA',
    long_name: 'ADVANCED CORRETORA DE CÂMBIO LTDA',
    compe_code: '117',
  },
  {
    ispb: '05790149',
    short_name: 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO',
    long_name:
      'Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP',
    compe_code: '114',
  },
  {
    ispb: '61723847',
    short_name: 'MAGLIANO S.A. CCVM',
    long_name: 'Magliano S.A. Corretora de Cambio e Valores Mobiliarios',
    compe_code: '113',
  },
  {
    ispb: '36113876',
    short_name: 'OLIVEIRA TRUST DTVM S.A.',
    long_name:
      'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.',
    compe_code: '111',
  },
  {
    ispb: '01800019',
    short_name: 'PORTOCRED S.A. - CFI',
    long_name: 'PORTOCRED S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO',
    compe_code: '108',
  },
  {
    ispb: '15114366',
    short_name: 'BCO BOCOM BBM S.A.',
    long_name: 'Banco Bocom BBM S.A.',
    compe_code: '107',
  },
  {
    ispb: '07652226',
    short_name: 'LECCA CFI S.A.',
    long_name: 'Lecca Crédito, Financiamento e Investimento S/A',
    compe_code: '105',
  },
  {
    ispb: '00360305',
    short_name: 'CAIXA ECONOMICA FEDERAL',
    long_name: 'CAIXA ECONOMICA FEDERAL',
    compe_code: '104',
  },
  {
    ispb: '02332886',
    short_name: 'XP INVESTIMENTOS CCTVM S/A',
    long_name:
      'XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A',
    compe_code: '102',
  },
  {
    ispb: '62287735',
    short_name: 'RENASCENCA DTVM LTDA',
    long_name: 'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
    compe_code: '101',
  },
  {
    ispb: '00806535',
    short_name: 'PLANNER CV S.A.',
    long_name: 'Planner Corretora de Valores S.A.',
    compe_code: '100',
  },
  {
    ispb: '03046391',
    short_name: 'UNIPRIME CENTRAL CCC LTDA.',
    long_name:
      'UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.',
    compe_code: '099',
  },
  {
    ispb: '78157146',
    short_name: 'CREDIALIANÇA CCR',
    long_name: 'Credialiança Cooperativa de Crédito Rural',
    compe_code: '098',
  },
  {
    ispb: '04632856',
    short_name: 'CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.',
    long_name: 'Credisis - Central de Cooperativas de Crédito Ltda.',
    compe_code: '097',
  },
  {
    ispb: '00997185',
    short_name: 'BCO B3 S.A.',
    long_name: 'Banco B3 S.A.',
    compe_code: '096',
  },
  {
    ispb: '11703662',
    short_name: 'TRAVELEX BANCO DE CÂMBIO S.A.',
    long_name: 'Travelex Banco de Câmbio S.A.',
    compe_code: '095',
  },
  {
    ispb: '11758741',
    short_name: 'BANCO FINAXIS',
    long_name: 'Banco Finaxis S.A.',
    compe_code: '094',
  },
  {
    ispb: '07945233',
    short_name: 'POLOCRED SCMEPP LTDA.',
    long_name:
      'PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT',
    compe_code: '093',
  },
  {
    ispb: '12865507',
    short_name: 'BRK S.A. CFI',
    long_name: 'BRK S.A. Crédito, Financiamento e Investimento',
    compe_code: '092',
  },
  {
    ispb: '01634601',
    short_name: 'CCCM UNICRED CENTRAL RS',
    long_name:
      'CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RIO GRANDE DO S',
    compe_code: '091',
  },
  {
    ispb: '62109566',
    short_name: 'CREDISAN CC',
    long_name: 'CREDISAN COOPERATIVA DE CRÉDITO',
    compe_code: '089',
  },
  {
    ispb: '11476673',
    short_name: 'BANCO RANDON S.A.',
    long_name: 'BANCO RANDON S.A.',
    compe_code: '088',
  },
  {
    ispb: '05463212',
    short_name: 'COOP CENTRAL AILOS',
    long_name: 'Cooperativa Central de Crédito - Ailos',
    compe_code: '085',
  },
  {
    ispb: '02398976',
    short_name: 'UNIPRIME NORTE DO PARANÁ - CC',
    long_name: 'UNIPRIME NORTE DO PARANÁ - COOPERATIVA DE CRÉDITO LTDA',
    compe_code: '084',
  },
  {
    ispb: '10690848',
    short_name: 'BCO DA CHINA BRASIL S.A.',
    long_name: 'Banco da China Brasil S.A.',
    compe_code: '083',
  },
  {
    ispb: '07679404',
    short_name: 'BANCO TOPÁZIO S.A.',
    long_name: 'BANCO TOPÁZIO S.A.',
    compe_code: '082',
  },
  {
    ispb: '10264663',
    short_name: 'BANCOSEGURO S.A.',
    long_name: 'BancoSeguro S.A.',
    compe_code: '081',
  },
  {
    ispb: '73622748',
    short_name: 'B&T CC LTDA.',
    long_name: 'B&T CORRETORA DE CAMBIO LTDA.',
    compe_code: '080',
  },
  {
    ispb: '09516419',
    short_name: 'BCO ORIGINAL DO AGRO S/A',
    long_name: 'Banco Original do Agronegócio S.A.',
    compe_code: '079',
  },
  {
    ispb: '34111187',
    short_name: 'HAITONG BI DO BRASIL S.A.',
    long_name: 'Haitong Banco de Investimento do Brasil S.A.',
    compe_code: '078',
  },
  {
    ispb: '00416968',
    short_name: 'BANCO INTER',
    long_name: 'Banco Inter S.A.',
    compe_code: '077',
  },
  {
    ispb: '07656500',
    short_name: 'BCO KDB BRASIL S.A.',
    long_name: 'Banco KDB do Brasil S.A.',
    compe_code: '076',
  },
  {
    ispb: '03532415',
    short_name: 'BCO ABN AMRO S.A.',
    long_name: 'Banco ABN Amro S.A.',
    compe_code: '075',
  },
  {
    ispb: '03017677',
    short_name: 'BCO. J.SAFRA S.A.',
    long_name: 'Banco J. Safra S.A.',
    compe_code: '074',
  },
  {
    ispb: '00000208',
    short_name: 'BRB - BCO DE BRASILIA S.A.',
    long_name: 'BRB - BANCO DE BRASILIA S.A.',
    compe_code: '070',
  },
  {
    ispb: '61033106',
    short_name: 'BCO CREFISA S.A.',
    long_name: 'Banco Crefisa S.A.',
    compe_code: '069',
  },
  {
    ispb: '02801938',
    short_name: 'BCO MORGAN STANLEY S.A.',
    long_name: 'BANCO MORGAN STANLEY S.A.',
    compe_code: '066',
  },
  {
    ispb: '48795256',
    short_name: 'BCO ANDBANK S.A.',
    long_name: 'Banco AndBank (Brasil) S.A.',
    compe_code: '065',
  },
  {
    ispb: '04332281',
    short_name: 'GOLDMAN SACHS DO BRASIL BM S.A',
    long_name: 'GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.',
    compe_code: '064',
  },
  {
    ispb: '04184779',
    short_name: 'BANCO BRADESCARD',
    long_name: 'Banco Bradescard S.A.',
    compe_code: '063',
  },
  {
    ispb: '03012230',
    short_name: 'HIPERCARD BM S.A.',
    long_name: 'Hipercard Banco Múltiplo S.A.',
    compe_code: '062',
  },
  {
    ispb: '04913129',
    short_name: 'CONFIDENCE CC S.A.',
    long_name: 'Confidence Corretora de Câmbio S.A.',
    compe_code: '060',
  },
  {
    ispb: '13009717',
    short_name: 'BCO DO EST. DE SE S.A.',
    long_name: 'Banco do Estado de Sergipe S.A.',
    compe_code: '047',
  },
  {
    ispb: '92702067',
    short_name: 'BCO DO ESTADO DO RS S.A.',
    long_name: 'Banco do Estado do Rio Grande do Sul S.A.',
    compe_code: '041',
  },
  {
    ispb: '03609817',
    short_name: 'BCO CARGILL S.A.',
    long_name: 'Banco Cargill S.A.',
    compe_code: '040',
  },
  {
    ispb: '04913711',
    short_name: 'BCO DO EST. DO PA S.A.',
    long_name: 'Banco do Estado do Pará S.A.',
    compe_code: '037',
  },
  {
    ispb: '06271464',
    short_name: 'BCO BBI S.A.',
    long_name: 'Banco Bradesco BBI S.A.',
    compe_code: '036',
  },
  {
    ispb: '90400888',
    short_name: 'BCO SANTANDER (BRASIL) S.A.',
    long_name: 'BANCO SANTANDER (BRASIL) S.A.',
    compe_code: '033',
  },
  {
    ispb: '33885724',
    short_name: 'BANCO ITAÚ CONSIGNADO S.A.',
    long_name: 'Banco Itaú Consignado S.A.',
    compe_code: '029',
  },
  {
    ispb: '03323840',
    short_name: 'BCO ALFA S.A.',
    long_name: 'Banco Alfa S.A.',
    compe_code: '025',
  },
  {
    ispb: '10866788',
    short_name: 'BCO BANDEPE S.A.',
    long_name: 'Banco Bandepe S.A.',
    compe_code: '024',
  },
  {
    ispb: '28127603',
    short_name: 'BCO BANESTES S.A.',
    long_name: 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO',
    compe_code: '021',
  },
  {
    ispb: '57839805',
    short_name: 'BCO TRICURY S.A.',
    long_name: 'Banco Tricury S.A.',
    compe_code: '018',
  },
  {
    ispb: '42272526',
    short_name: 'BNY MELLON BCO S.A.',
    long_name: 'BNY Mellon Banco S.A.',
    compe_code: '017',
  },
  {
    ispb: '04715685',
    short_name: 'CCM DESP TRÂNS SC E RS',
    long_name:
      'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI',
    compe_code: '016',
  },
  {
    ispb: '02819125',
    short_name: 'UBS BRASIL CCTVM S.A.',
    long_name:
      'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
    compe_code: '015',
  },
  {
    ispb: '09274232',
    short_name: 'STATE STREET BR S.A. BCO COMERCIAL',
    long_name: 'STATE STREET BRASIL S.A. ? BANCO COMERCIAL',
    compe_code: '014',
  },
  {
    ispb: '04866275',
    short_name: 'BANCO INBURSA',
    long_name: 'Banco Inbursa S.A.',
    compe_code: '012',
  },
  {
    ispb: '61809182',
    short_name: 'C.SUISSE HEDGING-GRIFFO CV S/A',
    long_name: 'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A',
    compe_code: '011',
  },
  {
    ispb: '81723108',
    short_name: 'CREDICOAMO',
    long_name: 'CREDICOAMO CREDITO RURAL COOPERATIVA',
    compe_code: '010',
  },
  {
    ispb: '33657248',
    short_name: 'BNDES',
    long_name: 'BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL',
    compe_code: '007',
  },
  {
    ispb: '07237373',
    short_name: 'BCO DO NORDESTE DO BRASIL S.A.',
    long_name: 'Banco do Nordeste do Brasil S.A.',
    compe_code: '004',
  },
  {
    ispb: '04902979',
    short_name: 'BCO DA AMAZONIA S.A.',
    long_name: 'BANCO DA AMAZONIA S.A.',
    compe_code: '003',
  },
  {
    ispb: '00000000',
    short_name: 'BCO DO BRASIL S.A.',
    long_name: 'Banco do Brasil S.A.',
    compe_code: '001',
  },
];
